# Generated by Django 6.0.6 on 2026-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("INSTRUCTOR", "Instructor"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=50,
            ),
        ),
    ]
