# Generated by Django 6.0.6 on 2026-06-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseAccess",
        ),
    ]
