# Generated by Django 6.0.6 on 2026-07-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_delete_courseaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="The instructor who created this course",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL (alternative to file upload)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="courses/videos/"),
        ),
    ]
